### ISSUE TITLE
jest dependency

### ISSUE THREAD

**Issue by einicher** [robert8888/mime-file-extension#2]
You have jest as a dependency. It blows up project size to 60MB. I do not see where you use it. Without it its just 113KB. What is jest for?

**Comment by robert8888** [comment]
There are some test made in file main.test.js but feel free to made what you need with this repo. Just copy whole project remove what you need and make your own repo/package. This is not complicated code the secret is the data file

**Comment by einicher** [comment]
ah, ok.
thx

**Comment by robert8888** [comment]
"jest" moved to devDependency
